use crate::field_meta::categories::TypeCategory;

/// Trait representing compile-time information about a struct field.
///
/// This trait is implemented by marker types generated by the derive macro.
/// Each field in a struct gets a corresponding marker type that implements this trait.
pub trait FieldInfo: Copy + 'static {
    /// Original field name in Rust code.
    const NAME: &'static str;
    /// Serialized name (may differ due to rename attributes).
    const SERIALIZED_NAME: &'static str;
    /// Category name as string (e.g., "numeric", "text").
    const CATEGORY_NAME: &'static str;
    /// Custom tags added via `#[field_tags(...)]`.
    const TAGS: &'static [&'static str];

    /// The Rust type of the field.
    type Value;
    /// The category marker type.
    type Category: TypeCategory;

    /// Checks if this field has the given tag.
    fn has_tag(tag: &str) -> bool {
        Self::TAGS.contains(&tag)
    }
}
